{{- if and (not .Values.auth.existingSecret) (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codex-lb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.auth.secretKeys.databaseUrl }}: {{ include "codex-lb.databaseUrl" . | quote }}
  {{ .Values.auth.secretKeys.encryptionKey }}: {{ .Values.encryptionKey | default "" | quote }}
{{- end }}
